// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmanrgwusskjueohceis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tYW5yZ3d1c3NranVlb2hjZWlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MTY4NTYsImV4cCI6MjA3MDM5Mjg1Nn0.9umb9hTKqUD0GWDaG6nXWiMfQ40hHW75RcPzHwDVqN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});